version: '3'
services:
    db:
        build:
            # Custom image for file permissions
            context: ./docker/mysql
            args:
                USER_UID: ${USER_UID}
        networks:
            default:
        volumes:
            - "./.data/db:/var/lib/mysql:delegated"
            - "./docker/mysql/performances.cnf:/etc/mysql/conf.d/performances.cnf"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PUBLIC_PMA_PORT}:80/tcp
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            frontproxynet:
                aliases:
                    - ${APP_NAMESPACE}_pma
            default:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_pma.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.rule=Host(${HOSTNAME_PMA})"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.service=${APP_NAMESPACE}_pma"

    app:
        # Need to pass all vars to docker env for Crontab and supervisor scripts
        env_file: "./.env"
        build:
            # Use Nginx
            context: ./docker/php-nginx-alpine
            # Use Apache
            #context: ./docker/php74-apache
            args:
                USER_UID: ${USER_UID}
        ports:
            - ${PUBLIC_APP_PORT}:80/tcp
        depends_on:
            - db
            - solr
        volumes:
            - ${ROADIZ_APP_PATH}:/var/www/html:cached
        networks:
            frontproxynet:
                aliases:
                    - ${APP_NAMESPACE}_app
            default:
        environment:
            APP_CACHE: ${APP_CACHE}
            TRUSTED_PROXIES: ${TRUSTED_PROXIES}
            USER_UID: ${USER_UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}
            BLACKFIRE_LOG_LEVEL: ${BLACKFIRE_LOG_LEVEL}
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
            BLACKFIRE_ENDPOINT: "https://blackfire.io"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}.rule=Host(${HOSTNAME})"
            - "traefik.http.routers.${APP_NAMESPACE}.service=${APP_NAMESPACE}"

    solr:
        build:
            # Custom image for file permissions
            context: ./docker/solr
            args:
                USER_UID: ${USER_UID}
        ports:
            - "${PUBLIC_SOLR_PORT}:8983/tcp"
        volumes:
            - "./.data/solr:/var/solr:delegated"
        environment:
            SOLR_UID: ${USER_UID}
            SOLR_GID: ${USER_UID}
        command:
            - solr-precreate
            - ${SOLR_CORE_NAME}
        networks:
            frontproxynet:
                aliases:
                    - ${APP_NAMESPACE}_solr
            default:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.server.port=8983"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_solr.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.rule=Host(${HOSTNAME_SOLR})"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.service=${APP_NAMESPACE}_solr"

    mailer:
        image: mailhog/mailhog
        ports:
            - ${PUBLIC_MAILER_PORT}:8025/tcp
        networks:
            frontproxynet:
                aliases:
                    - ${APP_NAMESPACE}_mailer
            default:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.server.port=8025"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.rule=Host(${HOSTNAME_MAILER})"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.service=${APP_NAMESPACE}_mailer"

    blackfire:
        image: blackfire/blackfire
        environment:
            # Exposes BLACKFIRE_* environment variables from the host
            BLACKFIRE_LOG_LEVEL: ${BLACKFIRE_LOG_LEVEL}
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}

    varnish:
        build:
            context: ./docker/varnish
        tmpfs: /usr/local/var/varnish:exec
        depends_on:
            - app
        links:
            - app:app
        ports:
            - ${PUBLIC_VARNISH_PORT}:80/tcp
        networks:
            frontproxynet:
                aliases:
                    - ${APP_NAMESPACE}_varnish
            default:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.passhostheader=true"
            # Listen HTTP
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.entrypoints=http"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.rule=Host(${HOSTNAME_VARNISH})"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.service=${APP_NAMESPACE}_varnish"

networks:
    frontproxynet:
        external: true
    # If you need to use port forwarding, fixing default gateway can be useful
    # to keep same host IP address between service restarts
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/16
